name: Node CI with Nexus IQ



on: 
  push: 
    branches: 
     - master 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: PWD
      run: |
        pwd
        ls -a 

    - name: NPM Install
      run: |
        npm install
  
    
    - name: PWD post build
      run: |
        pwd
        ls -a 
    
    - name: Nexus IQ Policy Evaluation
      uses: sonatype-nexus-community/iq-github-action@1.1.0
      with:
        serverUrl: ${{ secrets.nexusiq_url }}
        username: ${{ secrets.nexusiq_username }}
        password: ${{ secrets.nexusiq_password }}
        applicationId: juice-shop__ealagorm
        stage: Release
        target: .