name: Node CI with Nexus IQ



on: 
  push: 
    branches: 
     - master 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    
    - name: PWD
      run: |
        pwd
        ls -a 
    # # Use Java version required by project 
    # - name: Set up JDK 15
    #   uses: actions/setup-java@v1
    #   with:
    #     java-version: 15

    # - name: Build with Maven
    #   run: mvn clean package -DskipTests --file pom.xml

    #   # Change Java version required by IQ CLI
    # - name: Set up JDK 1.8
    #   uses: actions/setup-java@v1
    #   with:
    #     java-version: 1.8
    
    
    # - name: PWD
    #   run: |
    #     pwd
    #     ls -a 
    
    - name: Nexus IQ Policy Evaluation
      uses: sonatype-nexus-community/iq-github-action@1.1.0
      with:
        serverUrl: ${{ secrets.nexusiq_url }}
        username: ${{ secrets.nexusiq_username }}
        password: ${{ secrets.nexusiq_password }}
        applicationId: WebGoat__ealagorm
        stage: Release
        target: .